### ISSUE TITLE
Using speech recognition api endpoint?

### ISSUE THREAD

**Issue by vondiplo** [api-ai/api-ai-javascript#11]
Is it possible to use the speech recognition api endpoint through the javascript sdk? 
If so, how do I make sure the access_token I use remains secure?

**Comment by Gugic** [comment]
Hello, i suppose it's your topic on our forums: https://discuss.api.ai/t/javascript-api-access-token-usage-insecure/307 so you already have answer to it.

Separate speech recognition is available through TTS object, you can example in demo (https://github.com/api-ai/api-ai-javascript/blob/master/demo/js/app.js)
