### ISSUE TITLE
Demo app speaks Russian to you

### ISSUE THREAD

**Issue by snollygolly** [api-ai/api-ai-javascript#12]
For an English speaker using a demo written in English, having the TTS use Russian is kind of confusing.  I narrowed it down to a previous issue [#1] and this line: 

https://github.com/api-ai/api-ai-javascript/blob/master/demo/js/app.js#L151

Is having the demo speak Russian something that was done on purpose or an oversight?  I'm happy to issue a PR to change it to English.

**Comment by Gugic** [comment]
@snollygolly sorry for taking so long for answer and thank you for your request. Change that you ask for was committed some time ago, now demo uses English TTS.
