### ISSUE TITLE
Demo not working cannot connect to websocket

### ISSUE THREAD

**Issue by edoardo849** [api-ai/api-ai-javascript#14]
Hello, trying to connect to the websocket but I keep getting the message in the js console "use direct assignment property" and the connection just hangs... without opening nor closing. Thought was a firewall issue but I'm getting that from every device.

When trying to send a json message or record voice, I'm getting the following error from the console:

```

api.ai.min.js:16 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.e.startListening @ api.ai.min.js:16_start @ app.js:188App.start @ app.js:37onclick @ index.html:47

```

**Comment by Gugic** [comment]
We are working on that issue. Currently you can set console.api.ai instead of api.api.ai as working endpoint.

**Comment by edoardo849** [comment]
@Gugic champagne following yesterday's announcement went in the load balancer? :-P ;-)

**Comment by edoardo849** [comment]
@Gugic still no luck with the console.api.ai endpoint. Please give the details of the connection. I'm using:

```js

SERVER_PROTO = 'wss';
SERVER_DOMAIN = 'console.api.ai';
SERVER_PORT = '4435';
ACCESS_TOKEN = 'MY-TOKEN'; 
SERVER_VERSION = '20150910';
```

**Comment by Gugic** [comment]
@edoardo849 for me it's now ok for both console.api.ai and api.api.ai

```javascript
SERVER_PROTO = 'wss';
SERVER_DOMAIN = 'api.api.ai';
SERVER_PORT = '4435';
ACCESS_TOKEN = '';
SERVER_VERSION = '20150910';
```


```javascript
SERVER_PROTO = 'wss';
SERVER_DOMAIN = 'console.api.ai';
SERVER_PORT = '4435';
ACCESS_TOKEN = '';
SERVER_VERSION = '20150910';
```

Could you provide more details?

**Comment by edoardo849** [comment]
Started working for me too now! Thanks for your help!

**Comment by Gugic** [comment]
@edoardo849 by the way, we probably will stop serving websocket requests on api.api.ai endpoint in near future and we decided to create separate ws-only endpoint 'api-ws.api.ai'. You can already use it, SDK demo and docs are updated with that endpoint.

**Comment by repetix** [comment]
So, just to be clear, moving forward "api-ws.api.ai" will remain a valid endpoint for websockets?
