### ISSUE TITLE
Error on Androïd: No live audio input in this browser

### ISSUE THREAD

**Issue by guillaumegarcia13** [api-ai/api-ai-javascript#15]
Got a "No live audio input in this browser" on Chrome for Androïd.
Didn't see any prompt.

Let's say I am not bothered with the user typing the text instead of using the mic, how should I switch off the use of microphone?
Thanks.

**Comment by Gugic** [comment]
This library was designed to be used with mic only. In upcoming v2 will be simple text-query method and many other things (including ts support and npm bundle).

**Comment by Gugic** [comment]
Closed as outdated
