### ISSUE TITLE
WebSocket does not open on Demo page

### ISSUE THREAD

**Issue by redolent** [api-ai/api-ai-javascript#16]
Attached is a screenshot.

<img width="638" alt="screen shot 2016-10-07 at 13 36 22" src="https://cloud.githubusercontent.com/assets/650332/19203183/187de90a-8c93-11e6-8bc4-b2c723e5af23.png">

**Comment by Gugic** [comment]
You probably should allow usage of microphone to demo page.

**Comment by Gugic** [comment]
Closed as outdated
