### ISSUE TITLE
Add package to npm

### ISSUE THREAD

**Issue by jemhuntr** [api-ai/api-ai-javascript#20]
Is this official javascript package available in npm?

I would love to use this on an existing webpack build, but I can't find a maintanable way of doing it since I have to download the package again everytime I want to update.

The node js SDK is already available on npm, so why not this one too? This is the one I need since I'm only making a frontend app.

**Comment by Gugic** [comment]
Hello. There will be no official package for that SDK, but we are working on [v2](https://github.com/api-ai/api-ai-javascript/tree/v2). Actually you already can find [v2 beta](https://www.npmjs.com/package/api-ai-javascript) in npm, but I can't recommend to use it. it's unstable and SDK API may change in future.

**Comment by jemhuntr** [comment]
nice, thanks!

I'll keep an eye for that one :)
