### ISSUE TITLE
No way to use it without https ?

### ISSUE THREAD

**Issue by isbkch** [api-ai/api-ai-javascript#21]
I'm building my personal website, no audio inputs, just general information about my resume.. And people block their microphones when the browser asks for it.

**Comment by Gugic** [comment]
Sorry for late answer. You can try to use our html5 example (https://gist.github.com/Gugic/cfc008599fa9a82eeba4127648009132 ). Or JS SDK V2 beta (wich is available here in V2 branch and in npm).
