### ISSUE TITLE
Start and StopListening have wrong scope in StreamClient.ts

### ISSUE THREAD

**Issue by muuki88** [api-ai/api-ai-javascript#23]
Hi,

The [startListening](https://github.com/api-ai/api-ai-javascript/blob/v2/src/Stream/StreamClient.ts#L98) and the `stopListening` method both have the default scope, which is `window`.

Can be fixed with

```javascript
public startListening = () => {
  // ...
}
```

Typescript treats scopes exactly like javascript: https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript

**Comment by Gugic** [comment]
Hello, they are both are non-static members of StreamClient class and should work as expected (you should call them from already instantiated StreamClient object, in that case this refers to that object)

**Comment by muuki88** [comment]
Thanks for your response. Can you give an example how this should work?
I have a class encapsulating the stream client:

```ts
export default class ApiAiVoiceControl implements IVoiceControl {

  readonly streamClient: StreamClient;

  constructor(config: IVoiceControlConfig) {
    const client = new Client({
      accessToken: config.accessToken,
      lang: this.parseLang(config.lang)
    });
    this.streamClient = client.createStreamClient({
      onResults: this.onRecognitionResult,
      // ... some more callbacks
    });

    this.streamClient.init();
  }

  // calling this method results in an error
  startRecognition(): Promise<IServerResponse> {
     this.streamClient.open(); // throws error: 'onError is not defined'
  }
}
```

Calling `startRecognition` the context is set to `window` ( default if no specific context is  given ). When I call the method like this

```ts
this.streamClient.startListening.call(this.streamClient)
```

then everything works.

**Comment by Gugic** [comment]
i've tried to reproduce your issue, but was not succeed. 

With this listing (almost a direct copy of yours) 
```
class ApiAiVoiceControl {

    readonly streamClient: StreamClient;

    constructor() {
        const client = new Client({
            accessToken: ACCESS_TOKEN
        });
        this.streamClient = client.createStreamClient({
            onResults: this.onRecognitionResult,
        });
        this.streamClient.init();
    }

    onRecognitionResult(a) {
        console.log(arguments);
    }

    startRecognition() {
        this.streamClient.open();
    }
}
```

And compiled both with ES5 and ES6 modes i can not reproduce your problem. Everything seemed to work as designed.

Can you provide me with sources? (probably as zip-archive here)

**Comment by muuki88** [comment]
[This is my project](https://github.com/muuki88/daylight) where I had this bug. Somehow I refactor my app that I can't reproduce this error. I'm always puzzled by javascripts scoping :(

Sorry for the noise. If I get a small example working, I'll reopen the issue.
