### ISSUE TITLE
Challenge with International Characters (utf-8 issue)

### ISSUE THREAD

**Issue by elaval** [api-ai/api-ai-javascript#24]
Hi! I have been trying this API (in typescript) and it works very well in English.  But I am having some issues with international characters.

For example if I send the request:
"¿Cuál es la población de España?" (which is spanish for "What is the population in Spain?") 

It gets resolved (result.resolvedQuery) to:
"Â¿CuÃ¡l es la poblaciÃ³n de EspaÃ±a?"

I noticed that the problem is solved if the HTTPRequest was sent specifying the charset (utf-8) in the Content Type headers.

This could be achieved if line 43 in ts/XhrRequest.ts:
```
                headers["Content-Type"] = "application/json";
```

Is changed to:
```
                headers["Content-Type"] = "application/json; charset=utf-8";
```
It works OK and I get the right result.resolvedQuery:
"¿Cuál es la población de España?"

Sample code to reproduce the issue:
```
this.aiClient = new Client({accessToken: this.token});
this.aiClient.textRequest("¿Cuál es la población de España?")
    .then((response:any) => console.log(response.result.resolvedQuery));
```

**Comment by Gugic** [comment]
Should be fixed in beta.13, thank you for the report.
