### ISSUE TITLE
Export Interfaces.ts and Constants.ts

### ISSUE THREAD

**Issue by muuki88** [api-ai/api-ai-javascript#28]
Hi,

In order to write properly type classes it should be easy to access the relevant types.
At the moment I need to import `IServerResponse` like this

```typescript
import {IServerResponse} from '../../node_modules/api-ai-javascript/ts/Interfaces';

const response: IServerResponse = ...
```

It would be nice to import it like

```typescript
import {IServerResponse} from 'api-ai-javascript';
```

**Comment by Gugic** [comment]
Hello,

actually there are exported interfaces but only in explicit 'api-ai-javascript/ApiAiClient' module.
So this: `import {ApiAiClient, IServerResponse, IStreamClient} from "api-ai-javascript/ApiAiClient";` will actually work.

But you are right, i need to add this exports to index.ts and also i need to align documentation.

**Comment by Gugic** [comment]
Constants are now exported too, documentation updated

**Comment by muuki88** [comment]
Wuhuuuu 😍
