### ISSUE TITLE
Android Google Chrome issue

### ISSUE THREAD

**Issue by midofit** [api-ai/api-ai-javascript#30]
The current version doesn't seem to work with Google Chrome on Android. The reason seems to be `navigator.getUserMedia`, which is going to be deprecated. I tried using the `navigator.mediaDevices.getUserMedia` promise, but it doesn't work either.

**Comment by Gugic** [comment]
You still have working .textRequest. Just do not import StreamClient and use google chrome native [speech recognition](https://shapeshed.com/html5-speech-recognition-api/)

**Comment by midofit** [comment]
Good idea, thank you. So in the future we can only use textRequest with API.AI?

**Comment by Gugic** [comment]
I believe we will integrate some other services (and of course any possible local speechrec) at least in SDK's to make it transparent to do requests with ASR.

The big point is that our service is not about ASR at all.
Our company's main focus is NLU (natural language understanding) and dialog management. We provide a platform for creating conversational interfaces (called agents) for apps, bots, and devices. These interfaces are designed to receive text as input information.
