### ISSUE TITLE
Require error

### ISSUE THREAD

**Issue by ZwoRmi** [api-ai/api-ai-javascript#31]
I installled this package through `npm install api-ai-javascript` for my node app, using ecs6.

I require it using `var ApiAi = require('api-ai-javascript');`

And I have this error :
```
apppath\node_modules\api-ai-javascript\index.js:1
(function (exports, require, module, __filename, __dirname) { export * from "./srces6/_build";
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (appFileWhereRequireIsDone:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I can't understand why there is `export` in a `js` file, is that not only for `ts`?

I also try using this package with files under target path, but I had another error while running an example.
I prefer npm package.

How should I import and use your module?

**Comment by Gugic** [comment]
Hello!
And what actually are you trying to achieve?
api-ai-javascript is clientside-only library and it was not designed to work in node environment at all. You are trying to use requirejs or what?

Anywhay, `export` is a part of ECMAScript 2015 (6th edition) format, it's not about typescript, it's about [ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)   and sources folder called es6src.

Unfortunately modern browsers does not work with es6 modules (and with window.exports too), so to actually use it you should use some 3rd-party loader (like systemJS) or bundler (like browserify or webpack). And probably babel for transpilation (in case of using browserify at least). 

If you already use requireJS and something to bundle your code, it should not be a big problem to add additional transpilation from pure es6 to commonjs or something else.

For those who does not want all this pain, we have simple transpiled and compiled es5 version, that can be easily used like any other "oldschool" library.

**Comment by ZwoRmi** [comment]
Hello !

Well, I didn't notice that library was clientside only.
Thanks for all those informations, I will try something else for what I'm trying to achieve.

**Comment by Gugic** [comment]
By the way, we have separate nodejs SDK (
https://github.com/api-ai/api-ai-node-js)
