### ISSUE TITLE
Problem with Typescript 

### ISSUE THREAD

**Issue by chendetong1993** [api-ai/api-ai-javascript#34]
Hi, 
I need help. I installed api-ai with "npm install api-ai-javascript --save-dev", and put code 'import {ApiAiClient, ApiAiStreamClient} from "api-ai-javascript";'  in my code file. It shows lots of errors.

Typescript Error
Property 'AudioContext' does not exist on type 'Window'.
...opbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Request/TTSRequest.ts
        this.uri = Constants.DEFAULT_TTS_HOST;
        const AudioContext = window.AudioContext || webkitAudioContext;

Typescript Error
Cannot find name 'webkitAudioContext'.
...opbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Request/TTSRequest.ts
        this.uri = Constants.DEFAULT_TTS_HOST;
        const AudioContext = window.AudioContext || webkitAudioContext;

Typescript Error
Property 'AudioContext' does not exist on type 'Window'.
...ropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/Processors.ts
        _resamplerJSRegisterer();
        window.AudioContext = window.AudioContext || webkitAudioContext;

Typescript Error
Property 'AudioContext' does not exist on type 'Window'.
...ropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/Processors.ts
        _resamplerJSRegisterer();
        window.AudioContext = window.AudioContext || webkitAudioContext;

Typescript Error
Cannot find name 'webkitAudioContext'.
...ropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/Processors.ts
        _resamplerJSRegisterer();
        window.AudioContext = window.AudioContext || webkitAudioContext;

Typescript Error
Property 'AudioContext' does not exist on type 'Window'.
...pbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/StreamClient.ts
try {
    window.AudioContext = window.AudioContext || webkitAudioContext;
    navigator.getUserMedia =

Typescript Error
Property 'AudioContext' does not exist on type 'Window'.
...pbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/StreamClient.ts
try {
    window.AudioContext = window.AudioContext || webkitAudioContext;
    navigator.getUserMedia =

Typescript Error
Cannot find name 'webkitAudioContext'.
...pbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/StreamClient.ts
try {
    window.AudioContext = window.AudioContext || webkitAudioContext;
    navigator.getUserMedia =

Typescript Error
Property 'webkitGetUserMedia' does not exist on type 'Navigator'.
...pbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/StreamClient.ts
navigator.getUserMedia =
    navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
window.URL = window.URL || window.webkitURL;

Typescript Error
Property 'mozGetUserMedia' does not exist on type 'Navigator'.
...pbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/Stream/StreamClient.ts
navigator.getUserMedia =
    navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
window.URL = window.URL || window.webkitURL;

Typescript Error
Cannot find name 'ActiveXObject'.
.../Sync/Dropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/XhrRequest.ts
() => new XMLHttpRequest(),
() => new ActiveXObject("Msxml2.XMLHTTP"),
() => new ActiveXObject("Msxml3.XMLHTTP"),

Typescript Error
Cannot find name 'ActiveXObject'.
.../Sync/Dropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/XhrRequest.ts
() => new ActiveXObject("Msxml2.XMLHTTP"),
() => new ActiveXObject("Msxml3.XMLHTTP"),
() => new ActiveXObject("Microsoft.XMLHTTP")

Typescript Error
Cannot find name 'ActiveXObject'.
.../Sync/Dropbox/Websites/Cueat/App/node_modules/api-ai-javascript/ts/XhrRequest.ts
    () => new ActiveXObject("Msxml3.XMLHTTP"),
    () => new ActiveXObject("Microsoft.XMLHTTP")
];

Typescript Error
Supplied parameters do not match any signature of call target.
D:/Documents/Sync/Dropbox/Websites/Cueat/App/src/pages/home/home.ts
	M_RequestMenuByText(Text){
		const client = new ApiAiClient('YOUR_ACCESS_TOKEN', {streamClientClass: ApiAiStreamClient});
client

**Comment by Gugic** [comment]
Which version of typescript and node do you use?

**Comment by chendetong1993** [comment]
I am using Ionic 2 to develop a app.

**Comment by Gugic** [comment]
@chendetong1993 ok, i tried to build app with ionic 2 and api-ai-javascript

I face two build issues -  first was about ActiveXObject (i fix it and publish .beta16 with that fix and few linting-connected things) and a second was "Module build failed: Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/api-ai-javascript/index.js.map'" which i believe is ionic bug (.map files should generates during build, that is not the thing that should be distributed). So to make things work i was need to make this file myself:

> touch /path/to/project/node_modules/api-ai-javascript/index.js.map

Considering other errors (AudioContext, webkitGetUserMedia, etc.) - api-ai-javascript has @types/webaudioapi and @types/webrtc in "dependencies" show it should resolves (and it actually resolves in my case). Please, try beta.16 and if that errors still will present, try to install this two dependencies manually.

Thanks.

**Comment by Gugic** [comment]
beta.18 should solve other issues

**Comment by chendetong1993** [comment]
It works right now.  Thank you very much.

**Comment by cuzox** [comment]
I'm still having this issue, had to touch the file

**Comment by jgbolger** [comment]
Hi,

I am also having this issue.

- ionic 3.18.0
- Angular 5
- api-ai-javascript@2.0.0-beta.21

Error: Module build failed: Error: ENOENT: no such file or directory, open 'C:\Dev\workspace\chatbots\awc\mobile-app\faq-bot\node_modules\api-ai-javascript\index.js.map'

Any thoughts?

Thanks,
John

**Comment by gerhardcit** [comment]
@jgbolger , had same error, someone suggested you just create that empty file.
