### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by rosscdh** [api-ai/api-ai-javascript#4]
Hi there,

Great potential in this lib, thanks.

Copy pasting the code results in

```
WebSocket is already in CLOSING or CLOSED state.
```

which seems to break up the state? 

````
(function() {
  'use strict';

  angular
    .module('findr')
    .controller('MainController', MainController);

  /** @ngInject */
  function MainController($rootScope, $timeout, webDevTec, toastr) {
    var vm = this;
    var apiAi = new ApiAi($rootScope.apiAiConfig);

    vm.classAnimation = '';
    vm.Listening = false;

    activate();

    //
    // Private methods
    //
    function activate() {
      $timeout(function() {
        vm.classAnimation = 'rubberBand';
      }, 4000);
    }

    function processResult(data) {
      console.log('Processing api.ai data')
    }

    //
    // Scope methods
    //
    vm.startListening = function () {
      apiAi.init();
      vm.Listening = true;
    }

    vm.stopListening = function () {

      apiAi.stopListening();
      apiAi.close();

      vm.Listening = false;
    }

    //
    // Api ai events
    //
    apiAi.onInit = function () {
        console.log('onInit');
        apiAi.open();
    };

    apiAi.onOpen = function () {
        console.log('onOpen');
        console.log(apiAi.isOpen())
        apiAi.startListening();
    };

    apiAi.onClose = function () {
      console.log('onClose');
      vm.Listening = false;
      console.log(apiAi.isOpen())
    };

    apiAi.onStartListening = function () {
      console.log('onStartListening');
      vm.Listening = true;
    };
    /**
     * It's triggered when listening is stopped.
     */
    apiAi.onStopListening = function () {
      console.log('onStopListening');
      vm.Listening = false;
      console.log(apiAi.isOpen())
    };


// apiAi.onEvent = function (code, data) {
apiAi.onError = function (code, data) {
  console.log('onError')
  console.log(code)
  console.log(data)
};

    apiAi.onResults = function (data) {
        console.log('onResults');
        console.log(data)

        var status = data.status;

        var code;
        if (!(status && (code = status.code) && isFinite(parseFloat(code)) && code < 300 && code > 199)) {
            text.innerHTML = JSON.stringify(status);
            return;
        }
        processResult(data.result);
    };

  }
})();
````

Similar to this perhaps? https://github.com/faye/faye/issues/371

![demo](https://cloud.githubusercontent.com/assets/397106/12670997/f7471744-c66c-11e5-8d64-0931543a72b0.gif)

**Comment by Gugic** [comment]
Hello rosscdh, thank you for your words. 

Unfortunately i was unable to trigger that error with part of code you provide us with. Can you provide us with full application sources somehow?

Also, what version of browser and operating system do you using?

**Comment by rosscdh** [comment]
Hi there,

Thanks for that. Attached please find a zipfile of the gulp-angular play
project Im working on.

to get it going you will need to run npm install;bower install and then
gulp serve

Chromium: 40.0.2209.0
OSX: 10.9.5

Hope that helps.

Ross

**Comment by Gugic** [comment]
It seems that there no any archive attached, can you re-attach it (or send it directly to shingarev@api.ai)

**Comment by rosscdh** [comment]
Hm it's definitely there perhaps ur mail server removed it. Will resend

**Comment by rosscdh** [comment]
Hi @Gugic hope your weekend went well. Did you have any time to take a look at the strange websocket closed problem?

**Comment by rosscdh** [comment]
tracking it further am getting

```
"No async message support and buffer too small. Buffer size: [32,000], Message size: [30,214]
```

**Comment by Gugic** [comment]
@rosscdh 
I have your message with sources, thank you, but currently i was not succeed in reproducing of error from first message (ubuntu/chromium).

 I am going to do some experiments on other laptop (with mac os) and will post here when got  any results.

By the way, did you try to run your application on another environment?

**Comment by rosscdh** [comment]
Hey there,

Safari, Opera, Chromium all the same on the same machine.

V strange

**Comment by rosscdh** [comment]
Hmm it may be a result of using browsersync as per:
https://github.com/chimurai/http-proxy-middleware/issues/37

Which is strange because i was receiving response with contexts for about
30 mins.

**Comment by shekit** [comment]
Hey, I'm getting the same error in my app. I am not able to consistently reproduce this error. It seems to be triggered by a long period of inactivity within the app. I am calling stopListening() everytime though. Any clues yet?

**Comment by techpeace** [comment]
As @shekit mentioned, I'm seeing this error reliably after long periods of inactivity.

**Comment by techpeace** [comment]
Since I'm in a situation where I don't need the socket open constantly, I simply open the socket connection when I need to send a query, and otherwise keep it closed. I'd suggest a similar approach if you're running into this problem.

**Comment by faran234** [comment]
client2.js:1 WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ client2.js:1
client2.js:81 Got error Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
client.js:19 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.
(anonymous) @ client.js:19
client2.js:91 WebSocket is already in CLOSING or CLOSED state.
send @ client2.js:91
(anonymous) @ client2.js:15????how i can fix this error
