### ISSUE TITLE
Help Me To Get it working on Google Chrome

### ISSUE THREAD

**Issue by bhallaheemanshu** [api-ai/api-ai-javascript#5]
Hi Guys , I am trying the js demo on google chrome and getting this error 
>  ON ERROR 5 No live audio input in this browser

**Comment by artemgoncharuk** [comment]
Hi, are you testing from a local file system or have you deployed code to a server?
Which browser are you using?

**Comment by bhallaheemanshu** [comment]
I am using google chrome and yes i am running it on local server and also tried online

**Comment by Digikid13** [comment]
Make sure you are using HTTPS, chrome allow mic input for HTTP urls.

**Comment by Gugic** [comment]
I suppose i can close it, there were no any answers during a long time.

**Comment by bhallaheemanshu** [comment]
Sorry for late reply . Can anyone surely tell me is this api supports all browsers or specific one's

**Comment by Gugic** [comment]
It works in Microsoft Edge, Chromium-based browsers (chrome/opera/yandex/vivaldi/etc.), firefox and safari. Did not work in Microsoft Internet explorer.

**Comment by bhallaheemanshu** [comment]
ok thanks
