### ISSUE TITLE
Not receiving responses in electron app

### ISSUE THREAD

**Issue by shekit** [api-ai/api-ai-javascript#6]
Hi,

I'm using api.ai in an electron app however I am unable to get any results back.

My code looks like this:

```
var config = {
server: 'wss://api.api.ai:4435/api/ws/query',
token: 'my_access_token',// Use Client access token there (see agent keys).
sessionId: '1234'
};

var apiAi = new ApiAi(config);

apiAi.onInit = function(){
console.log("INITED");
apiAi.open();
}

apiAi.init();

$("link").on('click', function(){
apiAi.startListening();
})

apiAi.onStartListening = function(){
console.log("started listening")
}

apiAi.onResults = function(data){
console.log(data.result);
}
```

I am able to receive the debug message 'started listening' but I am not receiving any results back after that. However if I do apiAi.sendJson('data to send'), then I receive the results back which means I'm connecting to my agent correctly.

**Comment by shekit** [comment]
Hi, i got it working. there was some issue in my code however I keep getting websocket is already CLOSED or in CLOSING state. I am not able to consistently reproduce this error. It seems to be triggered by a long period of inactivity within the app. I am calling stopListening() everytime though.

**Comment by Gugic** [comment]
So i suppose i can close that one. That error being discussed in #4
