### ISSUE TITLE
Websocket connection closing without response.

### ISSUE THREAD

**Issue by JGHammink** [api-ai/api-ai-javascript#8]
We have been working on creating of a Prove of Concept integration for Voice support for our application last week and got the base working using the javascript API.
Since last weekend however the integration stopped working. The websocket connection is opened and closed without any feedback data send. Also it looks like the server does not receive any client data either.
Anyone an idea if anything has changed server side that cause the javascript api to stop working?

**Comment by Gugic** [comment]
@JGHammink 
Thank you for your feedback, please, try it now.

**Comment by Gugic** [comment]
No reply, so closing.
